package flying_potato;

import javax.swing.JOptionPane;

/**
 *
 * @author rames
 */
public class homepage extends javax.swing.JFrame {

    public homepage() {
        initComponents();
        this.setTitle("Homepage");
        this.setLocationRelativeTo(null);
        this.pack();
        adminlogin.setTitle("Admin Login");
        adminlogin.hide();
        user_name.setText(new temp().name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminlogin = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        prof_pass = new javax.swing.JPasswordField();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        user_name = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        orderfood = new javax.swing.JLabel();
        customersupp = new javax.swing.JLabel();
        eventbk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminlogin.setVisible(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Admin User");

        jLabel13.setText("Enter Profile Password:");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(6, 6, 6)
                .addComponent(submit)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prof_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(prof_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close)
                    .addComponent(submit))
                .addContainerGap())
        );

        javax.swing.GroupLayout adminloginLayout = new javax.swing.GroupLayout(adminlogin.getContentPane());
        adminlogin.getContentPane().setLayout(adminloginLayout);
        adminloginLayout.setHorizontalGroup(
            adminloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminloginLayout.setVerticalGroup(
            adminloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminloginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(adminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Welcome To Flying Potato");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 42, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/log-out.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/log-out.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 0, 36, 36));

        user_name.setBackground(new java.awt.Color(204, 153, 255));
        user_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_name.setForeground(new java.awt.Color(204, 255, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 23));

        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/user-gear.png"))); // NOI18N
        admin.setToolTipText("Admin");
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1, -1, -1));

        orderfood.setBackground(new java.awt.Color(255, 255, 255));
        orderfood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderfood.setForeground(new java.awt.Color(255, 255, 0));
        orderfood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/salad.png"))); // NOI18N
        orderfood.setText("Order Food");
        orderfood.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        orderfood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orderfood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderfood.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        orderfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderfoodMouseClicked(evt);
            }
        });
        getContentPane().add(orderfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 103, -1, -1));

        customersupp.setBackground(new java.awt.Color(255, 255, 255));
        customersupp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customersupp.setForeground(new java.awt.Color(255, 255, 0));
        customersupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/customer-service.png"))); // NOI18N
        customersupp.setText("Customer Support");
        customersupp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customersupp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customersupp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        customersupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customersuppMouseClicked(evt);
            }
        });
        getContentPane().add(customersupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        eventbk.setBackground(new java.awt.Color(255, 255, 255));
        eventbk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventbk.setForeground(new java.awt.Color(255, 255, 0));
        eventbk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/event.png"))); // NOI18N
        eventbk.setText("Event Booking");
        eventbk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventbk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eventbk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eventbk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventbkMouseClicked(evt);
            }
        });
        getContentPane().add(eventbk, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 103, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flying_potato/image/homepage.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new loginpage().setVisible(true);
        new temp().drop();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        adminlogin.show();
    }//GEN-LAST:event_adminMouseClicked

    private void orderfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderfoodMouseClicked
        new Orderfood().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderfoodMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if("Dheeraj1258@".equals(prof_pass.getText()))
        {
            new adminpage().setVisible(true);
            adminlogin.hide();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Password.");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        adminlogin.hide();
    }//GEN-LAST:event_closeActionPerformed

    private void eventbkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventbkMouseClicked
        // TODO add your handling code here:
        new book_event().show();
    }//GEN-LAST:event_eventbkMouseClicked

    private void customersuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customersuppMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new costumer_support().setVisible(true);
        
    }//GEN-LAST:event_customersuppMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JInternalFrame adminlogin;
    private javax.swing.JButton close;
    private javax.swing.JLabel customersupp;
    private javax.swing.JLabel eventbk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orderfood;
    private javax.swing.JPasswordField prof_pass;
    private javax.swing.JButton submit;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
